env: SKIP_INTERPRETER=true
dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - git clone https://github.com/TravisToolbox/pycodestyle-travis.git
install:
  - "pip install tox-travis"
  - "pip install ."
  - ./pycodestyle-travis/install.sh
script:
  - tox
  - ./pycodestyle-travis/scan.sh
