[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "taillight"
version = "0.6.1"
description = "A lightweight, thread-safe signals and slots library with priorities."
readme = "README.md"
requires-python = ">=3.10"
license = "WTFPL OR LicenseRef-LPRAB"
license-files = ["LICENSE"]
authors = [
  { name = "Elizabeth Ashford", email = "elizabeth.jennifer.myers+taillight@gmail.com" },
]
keywords = ["events", "signals", "slots"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
Documentation = "https://taillight.readthedocs.io/"
Issues = "https://github.com/Elizafox/taillight/issues"
Repository = "https://github.com/Elizafox/taillight"

[project.optional-dependencies]
dev = ["build>=1.2", "ruff>=0.12", "sphinx>=8.1", "tox>=4.20", "twine>=6.1"]

[tool.setuptools.packages.find]
include = ["taillight*"]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["B", "E", "F", "I", "UP"]

[tool.ruff.lint.per-file-ignores]
"taillight/__init__.py" = ["E402"]
