[tox]
envlist = py310,py311,py312,py313,py314

[testenv]
commands = python -m unittest discover -s tests

[testenv:lint]
skip_install = true
deps = ruff
commands = ruff check taillight doc/conf.py

[testenv:type]
skip_install = true
deps = mypy
commands = mypy

[testenv:docs]
deps = sphinx
commands = sphinx-build -W --keep-going -b html doc doc/_build/html
